"""Type signatures for Jinja's built-in filters and tests.

The stub module below is written next to the generated code and imported by it, so a
filtered expression carries a real type instead of collapsing to ``Any``:
``{{ items | length }}`` is an ``int`` and ``{% for x in items | sort %}`` still knows
what ``x`` is.

Only the return type is pinned. Every filter takes its value as ``Any`` (except where a
generic preserves the element type) and swallows the remaining arguments, because a
filter catalog that guesses at argument types reports errors on correct templates, and a
checker that cries wolf gets uninstalled. Filters absent from ``RETURNS`` keep the old
``Any`` behaviour rather than a signature nobody verified.
"""

from __future__ import annotations

MODULE_NAME = '_tj_filters'
TEST_STUB = '_tj_test'

TAGS: tuple[str, ...] = (
    'block',
    'call',
    'do',
    'elif',
    'else',
    'extends',
    'filter',
    'for',
    'from',
    'if',
    'import',
    'include',
    'macro',
    'raw',
    'set',
    'with',
)
"""Jinja statement tags worth completing after ``{%``. Closing tags follow from these."""

TESTS: tuple[str, ...] = (
    'boolean',
    'callable',
    'defined',
    'divisibleby',
    'eq',
    'escaped',
    'even',
    'false',
    'filter',
    'float',
    'ge',
    'gt',
    'in',
    'integer',
    'iterable',
    'le',
    'lower',
    'lt',
    'mapping',
    'ne',
    'none',
    'number',
    'odd',
    'sameas',
    'sequence',
    'string',
    'test',
    'true',
    'undefined',
    'upper',
)
"""Jinja's built-in tests, all of which evaluate to ``bool``."""

RETURNS: dict[str, str] = {
    'abs': '_TJAny',
    'attr': '_TJAny',
    'batch': 'Iterator[list[_T]]',
    'capitalize': 'str',
    'center': 'str',
    'count': 'int',
    'd': '_TJAny',
    'default': '_TJAny',
    'dictsort': 'list[tuple[_TJAny, _TJAny]]',
    'e': 'str',
    'escape': 'str',
    'filesizeformat': 'str',
    'first': '_T',
    'float': 'float',
    'forceescape': 'str',
    'format': 'str',
    'groupby': 'Iterator[_TJAny]',
    'indent': 'str',
    'int': 'int',
    'items': 'Iterator[tuple[_TJAny, _TJAny]]',
    'join': 'str',
    'last': '_T',
    'length': 'int',
    'list': 'list[_T]',
    'lower': 'str',
    'map': 'Iterator[_TJAny]',
    'max': '_T',
    'min': '_T',
    'pprint': 'str',
    'random': '_T',
    'reject': 'Iterator[_T]',
    'rejectattr': 'Iterator[_T]',
    'replace': 'str',
    'round': 'float',
    'safe': 'str',
    'select': 'Iterator[_T]',
    'selectattr': 'Iterator[_T]',
    'slice': 'Iterator[list[_T]]',
    'sort': 'list[_T]',
    'string': 'str',
    'striptags': 'str',
    'sum': '_TJAny',
    'title': 'str',
    'tojson': 'str',
    'trim': 'str',
    'truncate': 'str',
    'unique': 'Iterator[_T]',
    'upper': 'str',
    'urlencode': 'str',
    'urlize': 'str',
    'wordcount': 'int',
    'wordwrap': 'str',
    'xmlattr': 'str',
}
"""Return type per built-in filter. ``_T`` binds to the value's element type."""

_ELEMENTWISE = 'Iterable[_T]'
_HEADER = """\
\"""Generated by types-for-jinja. Signatures for Jinja's built-in filters and tests.\"""

from collections.abc import Iterable, Iterator
from typing import Any as _TJAny
from typing import TypeVar

_T = TypeVar('_T')


def _tj_test(value: _TJAny, /, *args: _TJAny, **kwargs: _TJAny) -> bool:
    raise NotImplementedError
"""


def stub_name(filter_name: str) -> str:
    """Return the generated function name for ``filter_name``."""
    return f'_tj_f_{filter_name}'


def module_source() -> str:
    """Render the importable module holding every filter signature.

    The bodies raise rather than being ``...`` because these are real modules, not stub
    files, and a checker is entitled to report an implicit ``None`` return against the
    declared type. Nothing ever calls them.
    """
    lines = [_HEADER]
    lines.extend(
        f'def {stub_name(name)}(value: {_value_type(returns)}, /, *args: _TJAny, **kwargs: _TJAny) -> {returns}:'
        '\n    raise NotImplementedError'
        for name, returns in sorted(RETURNS.items())
    )
    return '\n\n'.join(lines) + '\n'


def _value_type(returns: str) -> str:
    """A generic return has to bind ``_T``, which only the value argument can do."""
    return _ELEMENTWISE if '_T]' in returns or returns == '_T' else '_TJAny'
