"""Generate a typed Python wrapper that delegates rendering to Jinja.

The wrapper is the Level-1 codegen from the plan: a typed function whose call site
pyright checks, whose body calls ``_env.get_template(name).render(...)`` unchanged.
Jinja still renders. An optional ``validator`` adds Level-2 runtime enforcement,
either a ``@beartype`` guard (check, non-transforming) or a Pydantic ``TypeAdapter``
(parse and transform) applied to each parameter before the render call.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from typed_jinja.header import TemplateHeader

Validator = Literal['none', 'beartype', 'pydantic']


def generate_wrapper(
    header: TemplateHeader,
    template_name: str,
    *,
    validator: Validator = 'none',
    env_import: str | None = None,
    func_name: str | None = None,
) -> str:
    """Return Python source for a typed render wrapper around ``template_name``.

    ``env_import`` supplies the Jinja Environment as ``_env`` (for example
    ``from myapp.templating import env as _env``). When omitted, the module declares
    ``_env: Environment`` for the caller to assign. ``validator`` selects Level-2
    runtime enforcement. Imports are emitted in a stable order; run a formatter over
    the output if your project sorts imports.
    """
    name = func_name or _slug(template_name)
    signature = ', '.join(f'{param}: {type_str}' for param, type_str in header.params)
    call_kwargs = ', '.join(f'{param}={param}' for param, _ in header.params)

    lines = [
        f'"""Generated by typed-jinja from {template_name}. Do not edit by hand."""',
        '',
        'from __future__ import annotations',
        '',
        *_module_imports(header, validator, env_import),
    ]
    lines.extend(_module_globals(header, validator, env_import))
    lines.extend(['', ''])
    if validator == 'beartype':
        lines.append('@beartype')
    lines.extend(
        [
            f'def render_{name}(*, {signature}) -> Markup:',
            f'    """Render {template_name} with a checked context."""',
        ]
    )
    if validator == 'pydantic':
        lines.extend(
            f'    {param} = _ta_{param}.validate_python({param})  # validate and transform'
            for param, _ in header.params
        )
    render = f'_env.get_template({template_name!r}).render({call_kwargs})'
    lines.append(f'    return Markup({render})  # ruff:ignore[unsafe-markup-use]')
    return '\n'.join(lines) + '\n'


def _module_imports(header: TemplateHeader, validator: Validator, env_import: str | None) -> list[str]:
    imports = list(header.imports)
    env_line = env_import if env_import is not None else 'from jinja2 import Environment'
    imports.extend(['from markupsafe import Markup', env_line])
    if validator == 'beartype':
        imports.append('from beartype import beartype')
    if validator == 'pydantic':
        imports.append('from pydantic import TypeAdapter')
    return imports


def _module_globals(header: TemplateHeader, validator: Validator, env_import: str | None) -> list[str]:
    globals_: list[str] = []
    if env_import is None:
        globals_.extend(['', '_env: Environment'])
    if validator == 'pydantic':
        globals_.append('')
        globals_.extend(f'_ta_{param} = TypeAdapter({type_str})' for param, type_str in header.params)
    return globals_


def _slug(template_name: str) -> str:
    stem = Path(template_name).name.split('.', 1)[0]
    return ''.join(char if char.isalnum() else '_' for char in stem).strip('_')
