"""Generated by typed-jinja from profile.html.jinja. Do not edit by hand."""

from __future__ import annotations

from markupsafe import Markup
from pydantic import TypeAdapter

from examples.runtime.env import env as _env
from examples.runtime.models import Profile

_ta_profile = TypeAdapter(Profile)


def render_profile(*, profile: Profile) -> Markup:
    """Render profile.html.jinja with a checked context."""
    profile = _ta_profile.validate_python(profile)  # validate and transform
    return Markup(_env.get_template('profile.html.jinja').render(profile=profile))  # ruff:ignore[unsafe-markup-use]
