"""Generated by types-for-jinja from profile.html.jinja. Do not edit by hand."""

from __future__ import annotations

from beartype import beartype
from markupsafe import Markup

from examples.runtime.env import env as _env
from examples.runtime.models import Profile


@beartype
def render_profile(*, profile: Profile) -> Markup:
    """Render profile.html.jinja with a checked context."""
    return Markup(_env.get_template('profile.html.jinja').render(profile=profile))  # ruff:ignore[unsafe-markup-use]
